version: '3.8'

services:
  badminton-mongodb:
    image: mongo:7.0
    container_name: badminton-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=badminton_db

  badminton-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: badminton-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://badminton-mongodb:27017/badminton_db
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=30d
      - CLIENT_URL=${CLIENT_URL}
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - badminton-mongodb

  badminton-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: badminton-frontend
    restart: unless-stopped
    depends_on:
      - badminton-backend

volumes:
  mongodb_data:
  uploads_data:
